name: hangman
services:
  app:
    build: 
      context: .
      tags:
        - hangman-app:latest
      dockerfile: Dockerfile
    image: hangman-app:latest
    ports:
      - "8000:8080"
      - "8443:8443"
    # volumes:
    #   - ./:/var/www/html
    environment:
      PHP_OPCACHE_ENABLE: "1"
      SSL_MODE: "off"
      AUTORUN_ENABLED: true
  db:
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: